services:
    playerstage:
        hostname: ps
        build:
            context: ./
        container_name: playerstage
        volumes:
            - home:/home/erik
        ports:
            - 2225:22

volumes:
    home:
        external: true
        name: home

